config/routes.rb
Rails.application.routes.draw do
  get 'favourites/show'
  root :to => 'contacts#index'

  # resources is only for CRUD operations
  resources :users, :only => [:new, :create] # same as - :except => [:destroy]
  resources :contacts
  resources :groups
  # login is not CRUD
  get '/login' => 'session#new' # This will be our sign-in page.
  post '/login' => 'session#create' # This will be the path to which the sign-in form is posted
  delete '/login'=> 'session#destroy' # This will be the path users use to log-out.

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :user, :optional => true
  has_and_belongs_to_many :groups
  belongs_to :favourite, :optional => true

  validates :email, :phone, :presence => true, :uniqueness => true
end

app/models/favourite.rb
class Favourite < ApplicationRecord
  has_many :contacts
end

app/models/group.rb
class Group < ApplicationRecord
  has_and_belongs_to_many :contacts
  belongs_to :user, :optional => true
  validates_uniqueness_of :name, scope: :user_id    #scope allows for different users to have a group called "work"
                                                    #but each user can only have ONE group called "work"  
  validates :name, :presence => true                #backend validation - no empty string 
end

app/models/user.rb
class User < ApplicationRecord
  has_many :contacts
  has_many :groups
  has_secure_password

  validates :email, :presence => true, :uniqueness => true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :fetch_user

  private
  def fetch_user
    @current_user = User.find_by :id => session[:user_id] if session[:user_id].present?
    session[:user_id] = nil unless @current_user.present?
  end

  def check_for_login
    redirect_to login_path unless @current_user.present?
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def index
    if @current_user.present?
      @contacts = @current_user.contacts.paginate(:page => params[:page], :per_page => 6)
      @groups = @current_user.groups.uniq
    else
      @contacts = Contact.none
      @groups = Group.none
    end
    # @favourite = Favourite.find params [:id]
  end

  def new
    @contact = Contact.new
    @groups = @current_user.groups.uniq
  end

  def create
    @groups = @current_user.groups.uniq
    @contact = Contact.new contact_params
    @current_user.contacts << @contact

    if params[:file].present?
      req = Cloudinary::Uploader.upload(params[:file])
      @contact.photo = req["public_id"]
    end

    if @contact.save
      flash[:success] = "Successfully created new contact"
      redirect_to contacts_path
    else
      flash[:error] = "Failed to create new contact"
      render :new
    end
  end

  def edit
    @contact = Contact.find params[:id]
    @groups = @current_user.groups.uniq
  end

  def update
    contact = Contact.find params[:id]
    if params[:file].present?
      req = Cloudinary::Uploader.upload(params[:file])
      contact.photo = req["public_id"]
    end
    if
      contact.update_attributes(contact_params)
      contact.save
      flash[:success] = "Successfully updated contact"
      redirect_to contacts_path
    else
      render :edit
    end
  end

  def show
    @contact = Contact.find params[:id]
    @contacts = @current_user.contacts
    @groups = @current_user.groups.uniq
  end

  def destroy
    contact = Contact.find params[:id]
    contact.destroy
    flash[:success] = "Successfully deleted contact"
    redirect_to contacts_path
  end

  private
  def contact_params
    params.require(:contact).permit(:name, :email, :phone, :address, :company, group_ids: [])
  end
end

app/controllers/favourites_controller.rb
class FavouritesController < ApplicationController
  def show
    @favourite = Favourite.find params [:id]
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def new
    @group = Group.new
    @groups = @current_user.groups.uniq
  end

  def create
    group = Group.create group_params
    if group.save
      @current_user.groups << group
      flash[:success] = "Successfully created new group"
      redirect_to contacts_path
    else
      render :new
    end
  end

  def edit
    @group = Group.find params[:id]
    @groups = @current_user.groups.uniq
  end

  def update
    group = Group.find params[:id]
    group.update group_params
    redirect_to group
  end

  def show
    @group = Group.find params[:id]
    @groups = @current_user.groups.uniq
  end

  def destroy
    group = Group.find params[:id]
    group.destroy
    redirect_to root_path
  end

  private
  def group_params
    params.require(:group).permit(:name)
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
    # This is the action for user login. The view will have the login form template.
  end

  def create
    user = User.find_by :email => params[:email]
    if user.present? && user.authenticate(params[:password])
      session[:user_id] = user.id # Remember the user id from this moment on
      redirect_to root_path
    else
      flash[:error] = "Invalid email address or password"
      redirect_to login_path # we don't render on failure bacause we don't want to help a hacker
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to login_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save # Returns truthy value on success
      flash[:notice] = 'User was successfully created.'
      session[:user_id] = @user.id
      redirect_to root_path
    else
      flash.now[:error] = 'Could not create user.'
      render :new
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/favourites_helper.rb
module FavouritesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/contacts/edit.html.erb
<!-- When someone is LOGGED IN -->

<% if @current_user.present?%>
  <!-- Image logo and App name, Add Contact and Welcome User -->
  <nav class="navbar navbar-light sticky-top" style="background-color: #FFE8E2;">
    <%= link_to (image_tag("logo.png", :class => " mr-3d-inline-block align-top", :width => "34", :height => "34") + "RECONNECT"), root_path, :class => "navbar-brand" %>
      <ul class="navbar-nav">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Welcome,  <%= @current_user.name %>
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to "Logout", login_path, :method => "delete", :class => "dropdown-item" %>
          </div>
        </li>
      </ul>
  </nav>

  <div class="container">
    <div class="row mt-4">
      <! -- Groups and Favourites -->
      <div class="col-md-3">
        <div class="list-group shadow-sm bg-white rounded">
          <!-- add a plus/add icon to create a group -->
          <div class="btn-group dropright">
            <button type="button" class="btn btn-info dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Groups
            </button>
            <div class="dropdown-menu">
              <%= link_to "Create new group", new_group_path, :class => "dropdown-item" %>
              <%= link_to "Add new contact", new_contact_path, :class => "dropdown-item" %>
            </div>
          </div>
        </div>
          <% @groups.each do |group| %>
            <%= link_to group.name, group, :class => "list-group-item" %>
          <% end %>
      </div>
        <!-- to add favourites later -->
      <div class="col-md-9">
        <div class="title text-center col-md p-3">
          <h4><strong>Edit Contact</strong></h4>
        </div>
        <div class="container">
          <% if flash[:error].present? %>
            <p class="alert alert-danger p-2 text-center"><%= flash[:error] %></p>
          <% end %>
        </div>
        <%= render :partial => 'form' %>
      </div>
    </div>
  </div>
<% end %>

app/views/contacts/index.html.erb
<!-- When no user has logged in, home page with sign up/login form -->

<% if @current_user.nil?%>
  <!-- Image logo and app name -->
  <nav class="navbar navbar-light sticky-top" style="background-color: #FFE8E2;">
    <%= link_to (image_tag("logo.png", :class => "mr-3 d-inline-block align-top", :width => "34", :height => "34") + "RECONNECT"), root_path, :class => "navbar-brand" %>
  </nav>
    <!-- Login or Sign up form -->
    <div class="login-form">
      <%= form_tag login_path, class: 'border border-light p-5' do %>
        <p class="h4 mb-4 text-center">Log In</p>

        <!-- Email -->
        <%= label_tag :email %>
        <%= email_field_tag :email, nil, :class => "form-control mb-4", :placeholder => 'email@johndoe.com' %>

        <!-- Password -->
        <%= label_tag :password %>
        <%= password_field_tag :password, nil, :class => "form-control mb-4", :placeholder => 'Password' %>

        <!-- Login button -->
        <%= submit_tag "Log In", :class => "btn btn-info btn-block my-4" %>

        <!-- Sign Up -->
        <p class="text-center">
          Don't have an account?
          <%= link_to "Sign Up", new_user_path %>
        </p>
      <% end %>
    </div>
<% end %>

<!-- When someone is LOGGED IN -->

<% if @current_user.present?%>
  <!-- Image logo and App name, Add Contact and Welcome User -->
  <nav class="navbar navbar-light sticky-top" style="background-color: #FFE8E2;">
    <%= link_to (image_tag("logo.png", :class => "mr-3 d-inline-block align-top", :width => "34", :height => "34") + "RECONNECT"), root_path, :class => "navbar-brand" %>
      <ul class="navbar-nav">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Welcome,  <%= @current_user.name %>
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to "Logout", login_path, :method => "delete", :class => "dropdown-item" %>
          </div>
        </li>
      </ul>
  </nav>

  <div class="container">
    <div class="row mt-4">
      <! -- Groups and Favourites -->
      <div class="col-md-3">
        <div class="list-group shadow-sm bg-white rounded">
          <div class="btn-group dropright">
            <button type="button" class="btn btn-info dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Groups
            </button>
            <div class="dropdown-menu">
              <%= link_to "Create new group", new_group_path, :class => "dropdown-item" %>
              <%= link_to "Add new contact", new_contact_path, :class => "dropdown-item" %>
            </div>
          </div>
            <% @groups.each do |group| %>
              <%= link_to group.name, group, :class => "list-group-item" %>
            <% end %>
        </div>
        <!-- to add favourites later -->
        <!-- <div class="list-group">
          Favourites
          < @favourite.contacts.each do |contact| %>
            <li class="list-inline-item">
              < link_to contact.name, contact %>
            </li>
          < end %>
        </div> -->
      </div>
      <! -- Contacts List -->
      <div class="col-md-9">
        <div class="panel panel-default">
          <table class="table">
            <div class="row mt-4 justify-content-between">
              <div class="col col-lg-10">
                <h3><strong class="p-2">Contacts List</strong></h3>
              </div>
              <div class="col col-lg-2">
                <a href="/contacts/new"><i class="fas fa-user-plus p-3" title="Add new contact"></i></a>
              </div>
            </div>
            <div class="container">
              <% if flash[:success].present? %>
                <p class="alert alert-success p-2 text-center"><%= flash[:success] %></p>
              <% elsif flash[:notice].present? %>
                <p class="alert alert-info p-2 text-center"><%= flash[:notice] %></p>
              <% end %>
            </div>
          <% @contacts.each do |contact| %>
            <tr>
              <td class="middle">
                <div class="media">
                  <div class="media-left">
                    <% if contact.photo.present? %>
                      <%= cl_image_tag(contact.photo, :class => 'img-circle img-thumbnail') %>
                    <% else %>
                      <%= image_tag "no_pic.jpg", :width => "120", :height => "120", :class => "img-thumbnail" %>
                    <% end %>
                  </div>
                  <div class="media-body">
                    <h4 class="media-heading"><%= link_to contact.name, contact %></h4>
                      <address>
                        <strong><%= contact.email %></strong><br>
                        <%= contact.phone %>
                      </address>
                  </div>
                </div>
              </td>
              <td width="100" class="middle">
                <div class="row">
                  <div class="edit p-2">
                    <%= link_to edit_contact_path(contact) do %>
                      <i class="fas fa-edit" title="Edit"></i>
                    <% end %>
                  </div>
                  <div class="delete p-2">
                    <%= link_to contact, :method => "delete", :data => { :confirm => "Are you sure?" } do %>
                      <i class="fas fa-trash-alt" title="Delete"></i>
                    <% end %>
                  </div>
                </div>
              </td>
            </tr>
          <% end %>
          </table>
          <div class="text-center">
            <%= will_paginate(@contacts, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer) %>
          </div>
        </div
      </div>
    </div>
  </div>
<% end %>

app/views/contacts/new.html.erb
<!-- When someone is LOGGED IN -->

<% if @current_user.present?%>
  <!-- Image logo and App name, Add Contact and Welcome User -->
  <nav class="navbar navbar-light sticky-top" style="background-color: #FFE8E2;">
    <%= link_to (image_tag("logo.png", :class => "mr-3 d-inline-block align-top", :width => "34", :height => "34") + "RECONNECT"), root_path, :class => "navbar-brand" %>
      <ul class="navbar-nav">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Welcome,  <%= @current_user.name %>
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to "Logout", login_path, :method => "delete", :class => "dropdown-item" %>
          </div>
        </li>
      </ul>
  </nav>

  <div class="container">
    <div class="row mt-4">
      <! -- Groups and Favourites -->
      <div class="col-md-3">
        <div class="list-group shadow-sm bg-white rounded">
          <!-- add a plus/add icon to create a group -->
          <div class="btn-group dropright">
            <button type="button" class="btn btn-info dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Groups
            </button>
            <div class="dropdown-menu">
              <%= link_to "Create new group", new_group_path, :class => "dropdown-item" %>
              <%= link_to "Add new contact", new_contact_path, :class => "dropdown-item" %>
            </div>
          </div>
        </div>
          <% @groups.each do |group| %>
            <%= link_to group.name, group, :class => "list-group-item" %>
          <% end %>
      </div>
        <!-- to add favourites later -->
      <div class="col-md-9">
        <div class="title text-center col-md p-3">
          <h4><strong>New Contact</strong></h4>
        </div>
        <div class="container">
          <% if flash[:error].present? %>
            <p class="alert alert-danger p-2 text-center"><%= flash[:error] %></p>
          <% end %>
        </div>
        <%= render :partial => 'form' %>
      </div>
    </div>
  </div>
<% end %>

app/views/contacts/show.html.erb
<nav class="navbar navbar-light sticky-top" style="background-color: #FFE8E2;">
  <%= link_to (image_tag("logo.png", :class => "mr-3 d-inline-block align-top", :width => "34", :height => "34") + "RECONNECT"), root_path, :class => "navbar-brand" %>
    <ul class="navbar-nav">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Welcome,  <%= @current_user.name %>
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= link_to "Logout", login_path, :method => "delete", :class => "dropdown-item" %>
        </div>
      </li>
    </ul>
</nav>



<div class="container">
  <div class="row mt-4">
    <! -- Groups and Favourites -->
    <div class="col-md-3">
      <div class="list-group shadow-sm bg-white rounded">
        <!-- add a plus/add icon to create a group -->
        <div class="btn-group dropright">
          <button type="button" class="btn btn-info dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Groups
          </button>
          <div class="dropdown-menu">
            <%= link_to "Create new group", new_group_path, :class => "dropdown-item" %>
            <%= link_to "Add new contact", new_contact_path, :class => "dropdown-item" %>
          </div>
        </div>
          <% @groups.each do |group| %>
            <%= link_to group.name, group, :class => "list-group-item" %>
          <% end %>
      </div>
      <!-- to add favourites later -->
    </div>

    <div class="col-md-9 shadow p-3 mb-5 bg-white rounded">
      <div class="contacts-show">
        <div class="row top-heading">
          <div class="col">
            <div class="row">
              <div class="cloudinary">
                <% if @contact.photo.present? %>
                  <%= cl_image_tag(@contact.photo, :class => 'img-circle') %>
                <% end %>
              </div>
              <div class="name m-4">
              <h2><%= @contact.name %></h2>
              </div>
            </div>
          </div>
          <div class="col-md-auto">
          </div>
          <div class="col col-lg-3">
            <div class="row">

              <div class="p-3">
                <%= link_to contacts_path do %>
                  <i class="fas fa-address-book" title="Back to contacts list"></i>
                <% end %>
              </div>

              <div class="p-3">
                <%= link_to edit_contact_path(@contact) do %>
                  <i class="fas fa-edit" title="Edit"></i>
                <% end %>
              </div>

              <div class="p-3">
                <%= link_to @contact, :method => "delete", :data => { :confirm => "Are you sure?" } do %>
                  <i class="fas fa-trash-alt" title="Delete"></i>
                <% end %>
              </div>
            </div>
          </div>
        </div>
        <h4 class="m-4"><strong>Contact Details</strong></p>
        <div class="icon-details p-2">
          <div class="row m-2 mb-4">
            <div class="col-1">
              <i class="fas fa-envelope"></i>
            </div>
            <div class="col-11">
              <p><%= @contact.email %></p>
            </div>
          </div>
          <div class="row m-2 mb-4">
            <div class="col-1">
              <i class="fas fa-phone-alt"></i>
            </div>
            <div class="col-11">
              <p><%= @contact.phone %></p>
            </div>
          </div>
          <%  if @contact.address.present? %>
          <div class="row m-2 mb-4">
            <div class="col-1">
              <i class="fas fa-house-damage"></i>
            </div>
            <div class="col-11">
              <p><%= @contact.address %></p>
            </div>
          </div>
          <% end %>
          <% if @contact.company.present? %>
          <div class="row m-2 mb-4">
            <div class="col-1">
              <i class="fas fa-building"></i>
            </div>
            <div class="col-11">
              <p><%= @contact.company %></p>
            </div>
          </div>
          <% end %>
          <% if @contact.groups.present? %>
          <div class="row m-2">
            <div class="col-1">
              <i class="fas fa-users"></i>
            </div>
            <div class="col-11">
              <% @contact.groups.each do |group| %>
                <p><%= link_to group.name, group %></p>
              <% end %>
            </div
          </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/groups/_form.html.erb
<%= form_for @group do |f| %>
  <div class="form-group row">
    <%= f.label :name, 'Group Name', :class => "col-sm-3 col-form-label" %>
    <div class="col-sm-9">
      <%= f.text_field :name, :required => true, :autofocus => true, :placeholder => 'Insert Group Name', :class => "form-control" %>
    </div>
  </div>
  <div class="form-group row">
    <div class="col-sm-9">
    </div>
  </div>
  <div class="form-group row text-right">
    <div class="col-sm">
      <%= f.submit "Save", :class => "btn btn-info"  %>
      <%= link_to "Cancel", contacts_path, :class => "btn btn-default" %>
    </div>
  </div>
<% end %>

app/views/groups/edit.html.erb
<!-- When someone is LOGGED IN -->

<% if @current_user.present?%>
  <!-- Image logo and App name, Add Contact and Welcome User -->
  <nav class="navbar navbar-light sticky-top" style="background-color: #FFE8E2;">
    <%= link_to (image_tag("logo.png", :class => "mr-3 d-inline-block align-top", :width => "34", :height => "34") + "RECONNECT"), root_path, :class => "navbar-brand" %>
      <ul class="navbar-nav">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Welcome,  <%= @current_user.name %>
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to "Logout", login_path, :method => "delete", :class => "dropdown-item" %>
          </div>
        </li>
      </ul>
  </nav>

  <div class="container">
    <div class="row mt-4">
      <! -- Groups and Favourites -->
      <div class="col-md-3">
        <div class="list-group shadow-sm bg-white rounded">
          <!-- add a plus/add icon to create a group -->
          <div class="btn-group dropright">
            <button type="button" class="btn btn-info dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Groups
            </button>
            <div class="dropdown-menu">
              <%= link_to "Create new group", new_group_path, :class => "dropdown-item" %>
              <%= link_to "Add new contact", new_contact_path, :class => "dropdown-item" %>
            </div>
          </div>
        </div>
          <% @groups.each do |group| %>
            <%= link_to group.name, group, :class => "list-group-item" %>
          <% end %>
      </div>
        <!-- to add favourites later -->
      <div class="col-md-9">
        <div class="title text-center col-md p-3">
          <h4><strong>Edit Group</strong></h4>
        </div>
        <%= render :partial => 'form' %>
      </div>
    </div>
  </div>
<% end %>

app/views/groups/new.html.erb
<!-- When someone is LOGGED IN -->

<% if @current_user.present?%>
  <!-- Image logo and App name, Add Contact and Welcome User -->
  <nav class="navbar navbar-light sticky-top" style="background-color: #FFE8E2;">
    <%= link_to (image_tag("logo.png", :class => "mr-3 d-inline-block align-top", :width => "34", :height => "34") + "RECONNECT"), root_path, :class => "navbar-brand" %>
      <ul class="navbar-nav">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Welcome,  <%= @current_user.name %>
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to "Logout", login_path, :method => "delete", :class => "dropdown-item" %>
          </div>
        </li>
      </ul>
  </nav>

  <div class="container">
    <div class="row mt-4">
      <! -- Groups and Favourites -->
      <div class="col-md-3">
        <div class="list-group shadow-sm bg-white rounded">
          <!-- add a plus/add icon to create a group -->
          <div class="btn-group dropright">
            <button type="button" class="btn btn-info dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Groups
            </button>
            <div class="dropdown-menu">
              <%= link_to "Create new group", new_group_path, :class => "dropdown-item" %>
              <%= link_to "Add new contact", new_contact_path, :class => "dropdown-item" %>
            </div>
          </div>
        </div>
          <% @groups.each do |group| %>
            <%= link_to group.name, group, :class => "list-group-item" %>
          <% end %>
      </div>
        <!-- to add favourites later -->
      <div class="col-md-9">
        <div class="title text-center col-md p-3">
          <h4><strong>New Group</strong></h4>
        </div>
        <%= render :partial => 'form' %>
      </div>
    </div>
  </div>
<% end %>

app/views/groups/show.html.erb
<nav class="navbar navbar-light sticky-top" style="background-color: #FFE8E2;">
  <%= link_to (image_tag("logo.png", :class => "mr-3 d-inline-block align-top", :width => "34", :height => "34") + "RECONNECT"), root_path, :class => "navbar-brand" %>
    <ul class="navbar-nav">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Welcome,  <%= @current_user.name %>
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= link_to "Logout", login_path, :method => "delete", :class => "dropdown-item" %>
        </div>
      </li>
    </ul>
</nav>



<div class="container">
  <div class="row mt-4">
    <! -- Groups and Favourites -->
    <div class="col-md-3">
      <div class="list-group shadow-sm bg-white rounded">
        <!-- add a plus/add icon to create a group -->
        <div class="btn-group dropright">
          <button type="button" class="btn btn-info dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Groups
          </button>
          <div class="dropdown-menu">
            <%= link_to "Create new group", new_group_path, :class => "dropdown-item" %>
            <%= link_to "Add new contact", new_contact_path, :class => "dropdown-item" %>
          </div>
        </div>
          <% @groups.each do |group| %>
            <%= link_to group.name, group, :class => "list-group-item" %>
          <% end %>
      </div>
      <!-- to add favourites later -->
    </div>

    <div class="col-md-9 shadow p-3 mb-5 bg-white rounded">
      <div class="panel panel-default">
        <div class="row top-heading">
          <div class="col">
            <h2><%= @group.name %></h2>
          </div>
          <div class="col-md-auto">
          </div>
          <div class="col col-lg-3">
            <div class="row">

              <div class="p-3">
                <%= link_to contacts_path do %>
                  <i class="fas fa-address-book" title="Back to contacts list"></i>
                <% end %>
              </div>

              <div class="p-3">
                <%= link_to edit_group_path(@group) do %>
                  <i class="fas fa-edit" title="Edit"></i>
                <% end %>
              </div>

              <div class="p-3">
                <%= link_to @group, :method => "delete", :data => { :confirm => "Are you sure?" } do %>
                  <i class="fas fa-trash-alt" title="Delete"></i>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      <table class="table">
        <% @group.contacts.each do |contact| %>
        <tr>
          <td class="middle">
            <div class="media">
              <div class="media-left">
                <% if contact.photo.present? %>
                  <%= cl_image_tag(contact.photo, :class => 'img-circle img-thumbnail') %>
                <% else %>
                  <%= image_tag "no_pic.jpg", :width => "120", :height => "120", :class => "img-thumbnail" %>
                <% end %>
              </div>
              <div class="media-body">
                <h4 class="media-heading"><%= link_to contact.name, contact %></h4>
                  <address>
                    <strong><%= contact.email %></strong><br>
                    <%= contact.phone %>
                  </address>
              </div>
            </div>
          </td>
          <td width="100" class="middle">
            <div class="row">
              <div class="edit p-2">
                <%= link_to edit_contact_path(contact) do %>
                  <i class="fas fa-edit" title="Edit"></i>
                <% end %>
              </div>
              <div class="delete p-2">
                <%= link_to contact, :method => "delete", :data => { :confirm => "Are you sure?" } do %>
                  <i class="fas fa-trash-alt" title="Delete"></i>
                <% end %>
              </div>
            </div>
          </td>
        </tr>
        <% end %>
      </table>
    </div>